version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}

      - HERE_API_KEY=${HERE_API_KEY}
